-------Begin Transaction------
BEGIN;
UPDATE t3 SET (t3_c17, t3_c18, t3_c19, t3_c21) = (":-:|'t3_c17','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t3'|:-:", ":-:|'t3_c18','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t3'|:-:", ":-:|'t3_c19','INT8','NOT NULL','','','','','','UPDATE','t3'|:-:", ":-:|'t3_c21','VARCHAR(500)','NOT NULL','','','','','','UPDATE','t3'|:-:") WHERE ((t3_c3 = ":-:|'t3_c3','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:") AND (t3_c2 = ":-:|'t3_c2','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:")) AND (t3_c1 = ":-:|'t3_c1','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:") RETURNING t3_c4, t3_c5, t3_c6, t3_c7, t3_c8, t3_c9, t3_c10, t3_c11, t3_c12, t3_c13, t3_c14, t3_c15, t3_c16, t3_c17, CASE t3_c14 WHEN ":-:|'t3_c14','CHAR(2)','NOT NULL','','','','','','INSERT',''|:-:" THEN left(t3_c21, _) ELSE ":-:|'t3_c14','CHAR(2)','NOT NULL','','','','','','INSERT',''|:-:" END;
INSERT INTO t4(t4_c2, t4_c3, t4_c4, t4_c5, t4_c6, t4_c8, t4_c7, t4_c9) VALUES (":-:|'t4_c2','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c3','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c4','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c5','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c6','INT8','NOT NULL','PRIMARY KEY','','','','','INSERT','t4'|:-:", ":-:|'t4_c8','DECIMAL(6,2)','NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c7','TIMESTAMP','NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c9','VARCHAR(24)','NULL','','','','','','INSERT','t4'|:-:");
UPDATE t1 SET t1_c9 = t1_c9 + ":-:|'t1_c9','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t1'|:-:" WHERE t1_c1 = ":-:|'t1_c1','INT8','NOT NULL','PRIMARY KEY','','UNIQUE','','','WHERE','t1'|:-:" RETURNING t1_c2, t1_c3, t1_c4, t1_c5, t1_c6, t1_c7;
SELECT t3_c1 FROM t3 WHERE ((t3_c3 = ":-:|'t3_c3','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:") AND (t3_c2 = ":-:|'t3_c2','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:")) AND (t3_c6 = ":-:|'t3_c6','VARCHAR(16)','NOT NULL','','','','','','WHERE','t3'|:-:") ORDER BY t3_c4 ASC;
UPDATE t2 SET t2_c10 = t2_c10 + ":-:|'t2_c10','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t2'|:-:" WHERE (t2_c2 = ":-:|'t2_c2','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t2'|:-:") AND (t2_c1 = ":-:|'t2_c1','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t2'|:-:") RETURNING t2_c3, t2_c4, t2_c5, t2_c6, t2_c7, t2_c8;
COMMIT;
-------End Transaction-------
-------Begin Transaction------
BEGIN;
UPDATE t3 SET (t3_c17, t3_c18, t3_c19, t3_c21) = (":-:|'t3_c17','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t3'|:-:", ":-:|'t3_c18','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t3'|:-:", ":-:|'t3_c19','INT8','NOT NULL','','','','','','UPDATE','t3'|:-:", ":-:|'t3_c21','VARCHAR(500)','NOT NULL','','','','','','UPDATE','t3'|:-:") WHERE ((t3_c3 = ":-:|'t3_c3','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:") AND (t3_c2 = ":-:|'t3_c2','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:")) AND (t3_c1 = ":-:|'t3_c1','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t3'|:-:") RETURNING t3_c4, t3_c5, t3_c6, t3_c7, t3_c8, t3_c9, t3_c10, t3_c11, t3_c12, t3_c13, t3_c14, t3_c15, t3_c16, t3_c17, CASE t3_c14 WHEN ":-:|'t3_c14','CHAR(2)','NOT NULL','','','','','','INSERT',''|:-:" THEN left(t3_c21, _) ELSE ":-:|'t3_c14','CHAR(2)','NOT NULL','','','','','','INSERT',''|:-:" END;
INSERT INTO t4(t4_c2, t4_c3, t4_c4, t4_c5, t4_c6, t4_c8, t4_c7, t4_c9) VALUES (":-:|'t4_c2','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c3','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c4','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c5','INT8','NOT NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c6','INT8','NOT NULL','PRIMARY KEY','','','','','INSERT','t4'|:-:", ":-:|'t4_c8','DECIMAL(6,2)','NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c7','TIMESTAMP','NULL','','','','','','INSERT','t4'|:-:", ":-:|'t4_c9','VARCHAR(24)','NULL','','','','','','INSERT','t4'|:-:");
UPDATE t1 SET t1_c9 = t1_c9 + ":-:|'t1_c9','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t1'|:-:" WHERE t1_c1 = ":-:|'t1_c1','INT8','NOT NULL','PRIMARY KEY','','UNIQUE','','','WHERE','t1'|:-:" RETURNING t1_c2, t1_c3, t1_c4, t1_c5, t1_c6, t1_c7;
UPDATE t2 SET t2_c10 = t2_c10 + ":-:|'t2_c10','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','t2'|:-:" WHERE (t2_c2 = ":-:|'t2_c2','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t2'|:-:") AND (t2_c1 = ":-:|'t2_c1','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','t2'|:-:") RETURNING t2_c3, t2_c4, t2_c5, t2_c6, t2_c7, t2_c8;
COMMIT;
-------End Transaction-------
