// Copyright 2025 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

package workload_generator

import (
	"context"
	"database/sql"
	gosql "database/sql"
	"fmt"
	"github.com/lib/pq"
	"github.com/spf13/pflag"
	"gopkg.in/yaml.v3"
	"math/rand/v2"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/cockroachdb/cockroach-go/v2/crdb"
	"github.com/cockroachdb/cockroach/pkg/col/coldata"
	"github.com/cockroachdb/cockroach/pkg/sql/types"
	"github.com/cockroachdb/cockroach/pkg/util/bufalloc"
	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
	"github.com/cockroachdb/cockroach/pkg/workload"
	"github.com/cockroachdb/cockroach/pkg/workload/histogram"
	"github.com/cockroachdb/errors"
)

// runtimeColumn holds a generator and a cache of prior values.
type runtimeColumn struct {
	gen        Generator
	mu         sync.Mutex // protects gen and cache
	cache      []string   // ring buffer of recent values
	columnMeta ColumnMeta // metadata for this column
}

const (
	// Length of each field
	fieldLength   = 100
	baseBatchSize = 100
	maxCacheSize  = 100_000 // max size of the cache for each column

)

func init() {
	workload.Register(dbworkloadMeta)
}

var dbworkloadMeta = workload.Meta{
	Name:        "workload_generator",
	Description: "dbworkload tries to generate workloads from debug zip",
	Version:     "1.0.0",
	New: func() workload.Generator {
		g := &dbworkload{}
		g.flags.FlagSet = pflag.NewFlagSet("db_workload", pflag.ContinueOnError)
		g.flags.StringVar(&g.debugZip, "debug-zip", "",
			"path to unzipped debug zip")
		g.flags.StringVar(&g.dbName, "db-name", "", "database name")
		g.flags.IntVar(&g.rowCount, "rows", 1000,
			"base number of rows per table before FK‐depth scaling")
		g.flags.StringVar(&g.yamlLocation, "yaml", "", "location to write and read the <schema>.yaml file")
		g.flags.StringVar(&g.sqlLocation, "sql", "", "location to write and read the <schema>.sql file")
		g.flags.IntVar(&g.readPct, "read-pct", 50, " percentage of read transactions(0-100)")
		g.flags.Meta = map[string]workload.FlagMeta{}
		g.connFlags = workload.NewConnFlags(&g.flags)
		return g
	},
}

type dbworkload struct {
	flags     workload.Flags
	connFlags *workload.ConnFlags
	debugZip  string // path to the unzipped debug zip file
	dbName    string // database name to use for the workload
	rowCount  int    // base number of rows per table before FK‐depth scaling

	allSchema      map[string]*TableSchema //the table-schema map generated by parsing ddl statements
	createStmts    map[string]string       // table name → DDL string
	workloadSchema Schema                  // table name → []TableBlock : the yaml marshal-able schema

	yamlLocation string                    // location to write and read the <schema>.yaml file
	sqlLocation  string                    // location to write and read the <schema>.sql file
	readPct      int                       // percentage of read transactions
	columnGens   map[string]*runtimeColumn // table.col → runtimeColumn
}

// Meta implements the Generator interface.
func (*dbworkload) Meta() workload.Meta { return dbworkloadMeta }

// Flags implements the Flagser interface.
func (s *dbworkload) Flags() workload.Flags {
	return workload.Flags{
		FlagSet: s.flags.FlagSet,
	}
}

// ConnFlags implements the ConnFlagser interface.
func (s *dbworkload) ConnFlags() *workload.ConnFlags {
	return s.connFlags
}

func (s *dbworkload) Hooks() workload.Hooks {
	return workload.Hooks{
		//before data generation begins, we have to parse the DDLs and generate the schema required for further steps
		PreCreate: func(db *gosql.DB) error {
			//default for fall back
			dbName := s.Meta().Name
			//using the db override if provided
			if s.connFlags.DBOverride != "" {
				dbName = s.connFlags.DBOverride
			}
			//getting the debug zip location from the flags
			debug := s.debugZip
			//getting the schema and the DDl themselves from the debug folder
			schemas, createStmts, errDDL := GenerateDDLs(debug, dbName, false)
			s.allSchema = schemas
			s.createStmts = createStmts
			if errDDL != nil {
				return errors.Wrap(errDDL, "failed to generate DDLs")
			}
			//getting teh yaml marshal-able schema for data generation
			s.workloadSchema = buildWorkloadSchema(s.allSchema, dbName, s.rowCount)
			yamlData, err := yaml.Marshal(s.workloadSchema)
			if err != nil {
				return errors.Wrap(err, "failed to marshal workload schema to YAML")
			}
			//if a location was given, write the yaml there
			path := s.yamlLocation
			if path == "" {
				path = filepath.Join(os.TempDir(), "workload_schema.yaml")
			}
			if err := os.WriteFile(path, yamlData, 0644); err != nil {
				return errors.Wrapf(err, "could not write schema YAML to %s", path)
			}
			return nil
		},
	}
}

// Tables implements workload.Generator.Tables
func (d *dbworkload) Tables() []workload.Table {
	//tableOrder is the order in which the DDLs of different tables should be executed.
	//It currently assumes that the order in which the DDLs show up in the debug folder is the correct sequence
	tableOrder := getTableOrder(d.workloadSchema)
	// Finding the number of batches to generate for each table.
	// We use the maximum number of rows in any table to determine the number of batches.
	// Currently, we maintain the same number of batches across all tables, vary the batchSize if the rowCount varies.
	// Since our generators seeds are made using batch numbers, this helps to ensure foreign key constraints are held.
	maxRows := 0
	for _, tblBlocks := range d.workloadSchema {
		if tblBlocks[0].Count > maxRows {
			maxRows = tblBlocks[0].Count
		}
	}
	globalNumBatches := (maxRows + baseBatchSize - 1) / baseBatchSize

	var tables []workload.Table
	for _, tableName := range tableOrder {
		blocks := d.workloadSchema[tableName]
		block := blocks[0]
		total := block.Count
		batch_size_i := total / globalNumBatches

		tables = append(tables, workload.Table{
			Name:   tableName,
			Schema: generateSchema(d.createStmts[tableName]), // your short DDL string
			InitialRows: workload.BatchedTuples{
				NumBatches: globalNumBatches,
				FillBatch:  generateBatch(tableName, block, d.workloadSchema, batch_size_i, d),
			},
		})
	}
	return tables
}

// getTableOrder returns the order of tables based on their TableNumber in the schema.
// The table number was assigned based on position in the debug file.
func getTableOrder(rawSchema Schema) []string {
	tableOrder := make([]string, len(rawSchema))
	for tableName, blocks := range rawSchema {
		block := blocks[0]
		tableOrder[block.TableNumber] = tableName
	}
	return tableOrder
}

// generateSchema extracts the schema part from a CREATE TABLE statement.
// It strips the CREATE TABLE part and returns the column definitions and table constraints
func generateSchema(createStmt string) string {
	// find the first '('
	start := strings.Index(createStmt, "(")
	if start < 0 {
		return "" // or panic/empty, as you prefer
	}
	// walk forward, counting nested parens until we close the top‐level one
	depth := 0
	var end int
	for i := start; i < len(createStmt); i++ {
		switch createStmt[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				end = i
				// once we've closed the top‐level '(', we're done
				return createStmt[start : end+1]
			}
		}
	}
	// if we get here, the DDL was malformed (unbalanced parens)
	return createStmt[start:]
}

// generateBatch returns the FillBatch func for one table
// It generates a batch of data for the given table block
// INPUTS-
//   - tableName: the name of the table
//   - block: the TableBlock containing metadata about the table
//   - fullSchema: the full schema of the workload (the full amp of all TableBlocks)
//   - batchSize: the size of each batch to generate, since different tables have different batchSizes
//   - d: the dbworkload instance, which contains the generators and caches
func generateBatch(
	tableName string,
	block TableBlock,
	fullSchema Schema,
	batchSize int,
	d *dbworkload,
) func(batchIdx int, cb coldata.Batch, _ *bufalloc.ByteAllocator) {
	// determine the Cockroach columnar types and a stable column order
	colOrder := block.ColumnOrder
	// build Cockroach types in that order:
	cdTypes := make([]*types.T, len(colOrder))
	for i, colName := range colOrder {
		meta := block.Columns[colName]
		switch meta.Type {
		case "integer", "sequence":
			cdTypes[i] = types.Int
		case "float":
			cdTypes[i] = types.Float
		default:
			cdTypes[i] = types.Bytes
		}
	}

	return func(batchIdx int, cb coldata.Batch, _ *bufalloc.ByteAllocator) {
		total := block.Count
		start := batchIdx * batchSize
		end := start + batchSize
		if end > total {
			end = total
		}
		n := end - start

		//1) reset the vector; n rows, cdTypes[i] per column
		cb.Reset(cdTypes, n, coldata.StandardColumnFactory)

		// 2) instantiate one Generator per column, seeded by batchIdx
		gens := make([]Generator, len(colOrder))
		for i, colName := range colOrder {
			meta := block.Columns[colName]
			gens[i] = makeGenerator(meta, batchIdx, baseBatchSize, fullSchema)
		}

		// 3) fill row-by-row
		for row := 0; row < n; row++ {
			for i, cdType := range cdTypes {
				raw := gens[i].Next()

				vec := cb.ColVec(i)
				nulls := vec.Nulls()
				if raw == "" {
					nulls.SetNull(row)
					continue
				}
				switch cdType.Family() {
				case types.IntFamily:
					// sequences & integers
					iv, err := strconv.ParseInt(raw, 10, 64)
					if err != nil {
						panic(fmt.Sprintf("parse int: %v", err))
					}
					vec.Int64()[row] = iv

				case types.FloatFamily:
					// floats, decimals, numerics, doubles
					fv, err := strconv.ParseFloat(raw, 64)
					if err != nil {
						panic(fmt.Sprintf("parse float: %v", err))
					}
					vec.Float64()[row] = fv

				default:
					// strings, json, uuid, timestamp → bytes
					bytesVec := vec.Bytes()
					bytesVec.Set(row, []byte(raw))
				}
			}
		}
	}
}

// initGenerators seeds d.columnGens with both fresh generators and a cache
// of real values pulled from the live database.
func (d *dbworkload) initGenerators(db *sql.DB) error {
	// need globalNumBatches to seed the generators.
	// 0-globalNumBatches-1 was used during initial bulk insertions.
	// So, globalNumBatches can be the batch index for run time generators
	maxRows := 0
	for _, tblBlocks := range d.workloadSchema {
		if tblBlocks[0].Count > maxRows {
			maxRows = tblBlocks[0].Count
		}
	}
	globalNumBatches := (maxRows + baseBatchSize - 1) / baseBatchSize

	// 1) Build the generator + empty cache for every table.col
	d.buildRuntimeGenerators(globalNumBatches)

	// 2) Prime each cache by selecting up to maxInitialCacheSize existing rows.
	//    We do this column-by-column to keep it simple.
	err := d.setCacheValues(db)
	if err != nil {
		return err
	}
	return nil
}

func (d *dbworkload) setCacheValues(db *gosql.DB) error {
	for tableName, blocks := range d.workloadSchema {
		block := blocks[0]
		for _, colName := range block.ColumnOrder {
			key := fmt.Sprintf("%s", colName)
			rc := d.columnGens[key]

			// build a query like: SELECT colName FROM tableName LIMIT maxInitialCacheSize
			q := fmt.Sprintf(`SELECT %s FROM %s LIMIT %d`,
				pq.QuoteIdentifier(colName), pq.QuoteIdentifier(tableName), maxCacheSize)
			rows, err := db.QueryContext(context.Background(), q)
			if err != nil {
				return fmt.Errorf("priming cache for %s: %w", key, err)
			}

			for rows.Next() {
				var raw sql.NullString
				if err := rows.Scan(&raw); err != nil {
					rows.Close()
					return fmt.Errorf("scanning cache row for %s: %w", key, err)
				}
				if raw.Valid {
					rc.cache = append(rc.cache, raw.String)
				}
				if len(rc.cache) >= maxCacheSize {
					break
				}
			}
			rows.Close()
		}
	}
	return nil
}

func (d *dbworkload) buildRuntimeGenerators(globalNumBatches int) {
	d.columnGens = make(map[string]*runtimeColumn)
	for _, blocks := range d.workloadSchema {
		block := blocks[0]
		for colName, meta := range block.Columns {
			key := fmt.Sprintf("%s", colName)
			gen := makeGenerator(meta, globalNumBatches, baseBatchSize, d.workloadSchema)
			d.columnGens[key] = &runtimeColumn{
				gen:        gen,
				cache:      make([]string, 0, maxCacheSize),
				columnMeta: meta,
			}
		}
	}
}

func (d *dbworkload) Ops(
	ctx context.Context, urls []string, reg *histogram.Registry,
) (workload.QueryLoad, error) {

	err, err2, done := d.getYamlData()
	if done {
		return workload.QueryLoad{}, err2
	}
	// Parse transactions from the sql file.
	sqlPath := d.sqlLocation
	readTransactions, writeTransactions, err := readSQL(sqlPath)
	if err != nil {
		return workload.QueryLoad{}, err
	}

	db, err := gosql.Open("postgres", strings.Join(urls, " "))
	if err != nil {
		return workload.QueryLoad{}, err
	}
	db.SetMaxOpenConns(d.connFlags.Concurrency + 1)
	db.SetMaxIdleConns(d.connFlags.Concurrency + 1)

	//initialise teh generators and column old data caches
	if err := d.initGenerators(db); err != nil {
		return workload.QueryLoad{}, err
	}

	ql := workload.QueryLoad{}
	for i := 0; i < d.connFlags.Concurrency; i++ {
		worker := &txnWorker{
			db:                db,
			readTransactions:  readTransactions,
			writeTransactions: writeTransactions,
			rng:               rand.New(rand.NewPCG(uint64(time.Now().UnixNano()), uint64(i))),
			hists:             reg.GetHandle(),
			d:                 d, // reference to the dbworkload for generators
		}
		ql.WorkerFns = append(ql.WorkerFns, worker.run)
	}
	ql.Close = func(context.Context) error { return db.Close() }
	return ql, nil
}

func (d *dbworkload) getYamlData() (error, error, bool) {
	path := d.yamlLocation
	if path == "" {
		path = filepath.Join(os.TempDir(), "workload_schema.yaml")
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, errors.Wrapf(err, "could not read schema YAML from %s", path), true
	}
	if err := yaml.Unmarshal(raw, &d.workloadSchema); err != nil {
		return nil, errors.Wrap(err, "couldn't unmarshal schema YAML"), true
	}
	return err, nil, false
}

// getRegularColumnValue picks values from the generator or cache depending on sql clause or whether there is a fk dependency.
func (d *dbworkload) getRegularColumnValue(p Placeholder, idx int) string {
	key := fmt.Sprintf("%s", p.Name)
	rc := d.columnGens[key]
	rc.mu.Lock()
	defer rc.mu.Unlock()

	// for filling in data for where clause or columns with foreign key constraints, we use the cache.
	if p.Clause == "WHERE" || (rc.columnMeta.HasForeignKey == true) {
		if len(rc.cache) > 0 {
			return rc.cache[idx]
		}
	}
	// for insert or update clauses, we use the generator to get a new value.
	v := rc.gen.Next()
	if len(rc.cache) < maxCacheSize {
		rc.cache = append(rc.cache, v)
	} else {
		rc.cache[rand.IntN(len(rc.cache))] = v
	}
	return v
}

type txnWorker struct {
	db                *gosql.DB
	readTransactions  []Transaction
	writeTransactions []Transaction
	rng               *rand.Rand
	hists             *histogram.Histograms
	d                 *dbworkload // reference to the dbworkload for generators
	logFile           *os.File
}

// run executes a random transaction from the list of transactions.
func (w *txnWorker) run(ctx context.Context) error {
	var txn Transaction
	readPct := w.d.readPct
	if w.rng.IntN(100) < readPct {
		// choose from read transactions
		idx := w.rng.IntN(len(w.readTransactions))
		txn = w.readTransactions[idx]
	} else {
		// choose from write transactions
		idx := w.rng.IntN(len(w.writeTransactions))
		txn = w.writeTransactions[idx]
	}
	// reference to the dbworkload for generators
	d := w.d
	// Start time for the metrics I think.
	start := timeutil.Now()
	//inserted maintains a map of column names to the values that were inserted in this transaction
	inserted := make(map[string][]interface{})
	err := crdb.ExecuteTx(ctx, w.db, nil, func(tx *gosql.Tx) error {
		for _, sqlQuery := range txn.Queries {
			args := make([]interface{}, len(sqlQuery.Placeholders))
			//checking if we have a situation where all the primary keys in the query have foreign key dependency
			allPksAreFK := checkIfAllPkAreFk(sqlQuery, d)
			// Pick a single fkIdx for ALL FK placeholders (or -1 if none).
			//This ensures that for all column in a composite fk, the same row index from the parent column cache is chosen
			fkIndex := w.pickFkIndex(sqlQuery, d)
			// Build per-placeholder indexes
			indexes := w.setCacheIndex(sqlQuery, d, fkIndex)
			for i, placeholder := range sqlQuery.Placeholders {
				var raw string
				// Getting the value to be inserted for the placeholder
				raw = getColumnValue(allPksAreFK, placeholder, d, inserted, raw, indexes, i)
				// If the data was generated to be written, we need to insert it into the inserted map
				if placeholder.Clause == insert || placeholder.Clause == update {
					inserted[placeholder.Name] = append(inserted[placeholder.Name], raw)
				}
				// Set the value for the placeholder in the args slice based on the column type
				err := setColumnValue(raw, placeholder, args, i)
				if err != nil {
					return err
				}
			}
			// Run the SQL query with the args
			if _, err := tx.ExecContext(ctx, sqlQuery.SQL, args...); err != nil {
				return err
			}
		}
		return nil
	})
	// Calculate the elapsed time for the transaction metrics
	elapsed := timeutil.Since(start)
	w.hists.Get(fmt.Sprintf("typ_%v", txn.typ)).Record(elapsed)
	return err
}

// setColumnValue sets the value for a placeholder in the args slice.
func setColumnValue(raw string, placeholder Placeholder, args []interface{}, i int) error {
	var arg interface{}
	// If we got an empty string and this column is nullable, emit a SQL NULL.
	if raw == "" && placeholder.IsNullable {
		arg = setNullType(placeholder, arg)
	} else {
		// Otherwise parse the raw string into the right Go/sql type
		typedValue, err := setNotNullType(placeholder, raw, arg)
		if err != nil {
			return err
		}
		arg = typedValue
	}

	args[i] = arg
	return nil
}

// setNotNullType converts the raw string value to the appropriate SQL type based on the placeholder's column type.
func setNotNullType(placeholder Placeholder, raw string, arg interface{}) (interface{}, error) {
	switch t := strings.ToUpper(placeholder.ColType); {
	// integer types
	case strings.HasPrefix(t, "INT"):
		iv, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return nil, err
		}
		arg = sql.NullInt64{Int64: iv, Valid: true}
	// floating point types
	case strings.HasPrefix(t, "FLOAT"), strings.HasPrefix(t, "DECIMAL"), strings.HasPrefix(t, "NUMERIC"), strings.HasPrefix(t, "DOUBLE"):
		fv, err := strconv.ParseFloat(raw, 64)
		if err != nil {
			return nil, err
		}
		arg = sql.NullFloat64{Float64: fv, Valid: true}
	// boolean types
	case t == "BOOL", t == "BOOLEAN":
		bv, err := strconv.ParseBool(raw)
		if err != nil {
			return nil, err
		}
		arg = sql.NullBool{Bool: bv, Valid: true}
	// remaining types are parsed as raw strings
	default:
		// treat everything else as text/varchar/etc.
		arg = sql.NullString{String: raw, Valid: raw != ""}
	}
	return arg, nil
}

// setNullType sets the argument to a SQL NULL value based on the column type of the placeholder.
func setNullType(placeholder Placeholder, arg interface{}) interface{} {
	switch t := strings.ToUpper(placeholder.ColType); {
	case strings.HasPrefix(t, "INT"):
		arg = sql.NullInt64{Valid: false}
	case strings.HasPrefix(t, "FLOAT"), strings.HasPrefix(t, "DECIMAL"), strings.HasPrefix(t, "NUMERIC"), strings.HasPrefix(t, "DOUBLE"):
		arg = sql.NullFloat64{Valid: false}
	case t == "BOOL", t == "BOOLEAN":
		arg = sql.NullBool{Valid: false}
	default:
		arg = sql.NullString{Valid: false}
	}
	return arg
}

// getColumnValue retrieves the value for a placeholder based on its clause and whether it has a foreign key dependency.
func getColumnValue(allPksAreFK bool, p Placeholder, d *dbworkload, inserted map[string][]interface{}, raw string, indexes []int, i int) string {
	if allPksAreFK && (p.Clause == insert || p.Clause == update) {
		fk := d.columnGens[p.Name].columnMeta.FK
		parts := strings.Split(fk, ".")
		parentCol := parts[len(parts)-1] // last part is the column name
		if vals, ok := inserted[parentCol]; ok && len(vals) > 0 {
			raw = vals[0].(string)         // use the first value from the inserted map
			inserted[parentCol] = vals[1:] // remove the first value
		} else {
			//fallback that shouldn't really happen
			raw = d.getRegularColumnValue(p, indexes[i])
		}
	} else {
		raw = d.getRegularColumnValue(p, indexes[i])
	}
	return raw
}

// setCacheIndex sets the indexes for each placeholder in the SQL query.
// If the placeholder is a foreign key, it uses the fkIdx; otherwise, it picks a random index from the cache.
func (w *txnWorker) setCacheIndex(sqlQuery SQLQuery, d *dbworkload, fkIdx int) []int {
	indexes := make([]int, len(sqlQuery.Placeholders))
	for i, p := range sqlQuery.Placeholders {
		if d.columnGens[p.Name].columnMeta.HasForeignKey {
			indexes[i] = fkIdx
		} else {
			cacheLen := len(d.columnGens[p.Name].cache)
			indexes[i] = w.rng.IntN(cacheLen)
		}
	}
	return indexes
}

// pickFkIndex picks a random index from the cache of a foreign key column.
func (w *txnWorker) pickFkIndex(sqlQuery SQLQuery, d *dbworkload) int {
	fkIdx := -1
	for _, p := range sqlQuery.Placeholders {
		if d.columnGens[p.Name].columnMeta.HasForeignKey {
			cacheLen := len(d.columnGens[p.Name].cache)
			if cacheLen > 0 {
				fkIdx = w.rng.IntN(cacheLen)
			}
			break
		}
	}
	return fkIdx
}

// checkIfAllPkAreFk checks if all primary keys in the SQL query are foreign keys.
func checkIfAllPkAreFk(sqlQuery SQLQuery, d *dbworkload) bool {
	allPksAreFK := true
	for _, p := range sqlQuery.Placeholders {
		if p.IsPrimaryKey && !d.columnGens[p.Name].columnMeta.HasForeignKey {
			allPksAreFK = false
			break
		}
	}
	return allPksAreFK
}
