// Copyright 2025 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

package workload_generator

import (
	"context"
	"database/sql"
	gosql "database/sql"
	"fmt"
	"github.com/lib/pq"
	"github.com/spf13/pflag"
	"gopkg.in/yaml.v3"
	"math/rand/v2"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/cockroachdb/cockroach-go/v2/crdb"
	"github.com/cockroachdb/cockroach/pkg/col/coldata"
	"github.com/cockroachdb/cockroach/pkg/sql/types"
	"github.com/cockroachdb/cockroach/pkg/util/bufalloc"
	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
	"github.com/cockroachdb/cockroach/pkg/workload"
	"github.com/cockroachdb/cockroach/pkg/workload/histogram"
	"github.com/cockroachdb/errors"
)

// runtimeColumn holds a generator and a cache of prior values.
type runtimeColumn struct {
	gen        Generator
	mu         sync.Mutex // protects gen and cache
	cache      []string   // ring buffer of recent values
	columnMeta ColumnMeta // metadata for this column
}

const (
	// Length of each field
	fieldLength   = 100
	baseBatchSize = 100
	maxCacheSize  = 100_000 // max size of the cache for each column

)

func init() {
	workload.Register(dbworkloadMeta)
}

var dbworkloadMeta = workload.Meta{
	Name:        "workload_generator",
	Description: "workloadGeneratorStruct tries to generate workloads from debug zip",
	Version:     "1.0.0",
	New: func() workload.Generator {
		g := &workloadGeneratorStruct{}
		g.flags.FlagSet = pflag.NewFlagSet("db_workload", pflag.ContinueOnError)
		g.flags.StringVar(&g.debugLogsLocation, "debug-logs", "",
			"path to unzipped debug zip")
		g.flags.IntVar(&g.rowCount, "rows", 1000,
			"base number of rows per table before FK‐depth scaling")
		g.flags.StringVar(&g.inputYAML, "input-yaml", "",
			"path to an existing schema YAML file (if set, skip auto-dump)")
		g.flags.StringVar(&g.outputDir, "output-dir", ".",
			"directory to write generated schema and SQL files (default “.”)")
		g.flags.BoolVar(&g.schemaOnly, "schema-only", false,
			"dump schema YAML to output-dir and exit without building tables")
		g.flags.IntVar(&g.readPct, "read-pct", 50, " percentage of read transactions(0-100)")
		g.flags.Meta = map[string]workload.FlagMeta{}
		g.connFlags = workload.NewConnFlags(&g.flags)
		return g
	},
}

type workloadGeneratorStruct struct {
	flags             workload.Flags
	connFlags         *workload.ConnFlags
	debugLogsLocation string // path to the unzipped debug zip file
	dbName            string // database name to use for the workload
	rowCount          int    // base number of rows per table before FK‐depth scaling

	allSchema      map[string]*TableSchema //the table-schema map generated by parsing ddl statements
	createStmts    map[string]string       // table name → DDL string
	workloadSchema Schema                  // table name → []TableBlock : the yaml marshal-able schema

	inputYAML  string                    // path to “user-provided” schema YAML file
	outputDir  string                    // directory to write generated schema & SQL
	schemaOnly bool                      // if true, only dump schema and exit
	readPct    int                       // percent reads vs writes
	columnGens map[string]*runtimeColumn // table.col → runtimeColumn
}

// Meta implements the Generator interface.
func (*workloadGeneratorStruct) Meta() workload.Meta { return dbworkloadMeta }

// Flags implements the Flagser interface.
func (w *workloadGeneratorStruct) Flags() workload.Flags {
	return workload.Flags{
		FlagSet: w.flags.FlagSet,
	}
}

// ConnFlags implements the ConnFlagser interface.
func (w *workloadGeneratorStruct) ConnFlags() *workload.ConnFlags {
	return w.connFlags
}

func (w *workloadGeneratorStruct) Hooks() workload.Hooks {
	return workload.Hooks{
		//before data generation begins, we have to parse the DDLs and generate the schema required for further steps
		PreCreate: func(db *gosql.DB) error {
			// 1) Determine the database name (use --db override if set).
			dbName := w.Meta().Name
			if w.connFlags.DBOverride != "" {
				dbName = w.connFlags.DBOverride
			}
			w.dbName = dbName

			// 2) Parse DDLs out of the debug logs.
			schemas, stmts, err := GenerateDDLs(w.debugLogsLocation, w.dbName, false)
			if err != nil {
				return errors.Wrap(err, "failed to generate DDLs from debug logs")
			}
			w.allSchema, w.createStmts = schemas, stmts

			// 3a) Auto-generate (or) load schema YAML
			if w.inputYAML == "" {
				w.workloadSchema = buildWorkloadSchema(w.allSchema, w.dbName, w.rowCount)
				data, err := yaml.Marshal(w.workloadSchema)
				if err != nil {
					return errors.Wrap(err, "failed to marshal workload schema to YAML")
				}
				yamlPath := filepath.Join(w.outputDir, fmt.Sprintf("schema_%s.yaml", w.dbName))
				if err := os.WriteFile(yamlPath, data, 0644); err != nil {
					return errors.Wrapf(err, "failed to write schema YAML to %s", yamlPath)
				}
			} else {
				raw, err := os.ReadFile(w.inputYAML)
				if err != nil {
					return errors.Wrapf(err, "failed to read schema YAML from %s", w.inputYAML)
				}
				if err := yaml.Unmarshal(raw, &w.workloadSchema); err != nil {
					return errors.Wrapf(err, "failed to unmarshal schema YAML from %s", w.inputYAML)
				}
			}

			// 3b) Always generate the SQL file (even in schema-only mode).
			if err := GenerateWorkload(w.debugLogsLocation, w.allSchema, w.dbName, w.outputDir); err != nil {
				return errors.Wrapf(err,
					"failed to generate SQL workload to %s_read.sql and %s_write.sql",
					w.dbName, w.dbName,
				)
			}

			return nil
		},
	}
}

// Tables implements workload.Generator.Tables
func (w *workloadGeneratorStruct) Tables() []workload.Table {
	//if we are in yaml output mode, emit no tables
	if w.schemaOnly {
		return []workload.Table{}
	}

	//tableOrder is the order in which the DDLs of different tables should be executed.
	//It currently assumes that the order in which the DDLs show up in the debug folder is the correct sequence
	tableOrder := getTableOrder(w.workloadSchema)
	// Finding the number of batches to generate for each table.
	// We use the maximum number of rows in any table to determine the number of batches.
	// Currently, we maintain the same number of batches across all tables, vary the batchSize if the rowCount varies.
	// Since our generators seeds are made using batch numbers, this helps to ensure foreign key constraints are held.
	maxRows := 0
	for _, tblBlocks := range w.workloadSchema {
		if tblBlocks[0].Count > maxRows {
			maxRows = tblBlocks[0].Count
		}
	}
	globalNumBatches := (maxRows + baseBatchSize - 1) / baseBatchSize

	var tables []workload.Table
	for _, tableName := range tableOrder {
		blocks := w.workloadSchema[tableName]
		block := blocks[0]
		total := block.Count
		batch_size_i := total / globalNumBatches

		tables = append(tables, workload.Table{
			Name:   tableName,
			Schema: generateSchema(w.createStmts[tableName]), // your short DDL string
			InitialRows: workload.BatchedTuples{
				NumBatches: globalNumBatches,
				FillBatch:  generateBatch(tableName, block, w.workloadSchema, batch_size_i, w),
			},
		})
	}
	return tables
}

// getTableOrder returns the order of tables based on their TableNumber in the schema.
// The table number was assigned based on position in the debug file.
func getTableOrder(rawSchema Schema) []string {
	tableOrder := make([]string, len(rawSchema))
	for tableName, blocks := range rawSchema {
		block := blocks[0]
		tableOrder[block.TableNumber] = tableName
	}
	return tableOrder
}

// generateSchema extracts the schema part from a CREATE TABLE statement.
// It strips the CREATE TABLE part and returns the column definitions and table constraints
func generateSchema(createStmt string) string {
	// find the first '('
	start := strings.Index(createStmt, "(")
	if start < 0 {
		return "" // or panic/empty, as you prefer
	}
	// walk forward, counting nested parens until we close the top‐level one
	depth := 0
	var end int
	for i := start; i < len(createStmt); i++ {
		switch createStmt[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				end = i
				// once we've closed the top‐level '(', we're done
				return createStmt[start : end+1]
			}
		}
	}
	// if we get here, the DDL was malformed (unbalanced parens)
	return createStmt[start:]
}

// generateBatch returns the FillBatch func for one table
// It generates a batch of data for the given table block
// INPUTS-
//   - tableName: the name of the table
//   - block: the TableBlock containing metadata about the table
//   - fullSchema: the full schema of the workload (the full amp of all TableBlocks)
//   - batchSize: the size of each batch to generate, since different tables have different batchSizes
//   - d : the workloadGeneratorStruct instance, which contains the generators and caches
func generateBatch(
	tableName string,
	block TableBlock,
	fullSchema Schema,
	batchSize int,
	d *workloadGeneratorStruct,
) func(batchIdx int, cb coldata.Batch, _ *bufalloc.ByteAllocator) {
	// determine the Cockroach columnar types and a stable column order
	colOrder := block.ColumnOrder
	// build Cockroach types in that order:
	cdTypes := make([]*types.T, len(colOrder))
	for i, colName := range colOrder {
		meta := block.Columns[colName]
		switch meta.Type {
		case "integer", "sequence":
			cdTypes[i] = types.Int
		case "float":
			cdTypes[i] = types.Float
		default:
			cdTypes[i] = types.Bytes
		}
	}

	return func(batchIdx int, cb coldata.Batch, _ *bufalloc.ByteAllocator) {
		total := block.Count
		start := batchIdx * batchSize
		end := start + batchSize
		if end > total {
			end = total
		}
		n := end - start

		//1) reset the vector; n rows, cdTypes[i] per column
		cb.Reset(cdTypes, n, coldata.StandardColumnFactory)

		// 2) instantiate one Generator per column, seeded by batchIdx
		gens := make([]Generator, len(colOrder))
		for i, colName := range colOrder {
			meta := block.Columns[colName]
			gens[i] = makeGenerator(meta, batchIdx, baseBatchSize, fullSchema)
		}

		// 3) fill row-by-row
		for row := 0; row < n; row++ {
			for i, cdType := range cdTypes {
				raw := gens[i].Next()

				vec := cb.ColVec(i)
				nulls := vec.Nulls()
				if raw == "" {
					nulls.SetNull(row)
					continue
				}
				switch cdType.Family() {
				case types.IntFamily:
					// sequences & integers
					iv, err := strconv.ParseInt(raw, 10, 64)
					if err != nil {
						panic(fmt.Sprintf("parse int: %v", err))
					}
					vec.Int64()[row] = iv

				case types.FloatFamily:
					// floats, decimals, numerics, doubles
					fv, err := strconv.ParseFloat(raw, 64)
					if err != nil {
						panic(fmt.Sprintf("parse float: %v", err))
					}
					vec.Float64()[row] = fv

				default:
					// strings, json, uuid, timestamp → bytes
					bytesVec := vec.Bytes()
					bytesVec.Set(row, []byte(raw))
				}
			}
		}
	}
}

// initGenerators seeds d.columnGens with both fresh generators and a cache
// of real values pulled from the live database.
func (w *workloadGeneratorStruct) initGenerators(db *sql.DB) error {
	// need globalNumBatches to seed the generators.
	// 0-globalNumBatches-1 was used during initial bulk insertions.
	// So, globalNumBatches can be the batch index for run time generators
	maxRows := 0
	for _, tblBlocks := range w.workloadSchema {
		if tblBlocks[0].Count > maxRows {
			maxRows = tblBlocks[0].Count
		}
	}
	globalNumBatches := (maxRows + baseBatchSize - 1) / baseBatchSize

	// 1) Build the generator + empty cache for every table.col
	w.buildRuntimeGenerators(globalNumBatches)

	// 2) Prime each cache by selecting up to maxInitialCacheSize existing rows.
	//    We do this column-by-column to keep it simple.
	err := w.setCacheValues(db)
	if err != nil {
		return err
	}
	return nil
}

// setCacheValues fills into the runtimeColumn structs the cache data consisting of values generated during the initial bulk insert.
func (w *workloadGeneratorStruct) setCacheValues(db *gosql.DB) error {
	for tableName, blocks := range w.workloadSchema {
		block := blocks[0]
		for _, colName := range block.ColumnOrder {
			key := fmt.Sprintf("%s.%s", tableName, colName)
			rc := w.columnGens[key]

			// build a query like: SELECT colName FROM tableName LIMIT maxInitialCacheSize
			q := fmt.Sprintf(`SELECT %s FROM %s LIMIT %d`,
				pq.QuoteIdentifier(colName), pq.QuoteIdentifier(tableName), maxCacheSize)
			rows, err := db.QueryContext(context.Background(), q)
			if err != nil {
				return fmt.Errorf("priming cache for %s: %w", key, err)
			}

			for rows.Next() {
				var raw sql.NullString
				if err := rows.Scan(&raw); err != nil {
					rows.Close()
					return fmt.Errorf("scanning cache row for %s: %w", key, err)
				}
				if raw.Valid {
					rc.cache = append(rc.cache, raw.String)
				}
				if len(rc.cache) >= maxCacheSize {
					break
				}
			}
			rows.Close()
		}
	}
	return nil
}

func (w *workloadGeneratorStruct) buildRuntimeGenerators(globalNumBatches int) {
	w.columnGens = make(map[string]*runtimeColumn)
	for tableNmae, blocks := range w.workloadSchema {
		block := blocks[0]
		for colName, meta := range block.Columns {
			key := fmt.Sprintf("%s.%s", tableNmae, colName)
			gen := makeGenerator(meta, globalNumBatches, baseBatchSize, w.workloadSchema)
			w.columnGens[key] = &runtimeColumn{
				gen:        gen,
				cache:      make([]string, 0, maxCacheSize),
				columnMeta: meta,
			}
		}
	}
}

func (w *workloadGeneratorStruct) Ops(
	ctx context.Context, urls []string, reg *histogram.Registry,
) (workload.QueryLoad, error) {
	//Set database name in the main workload struct.
	w.setDbName()
	//Load the schema information into memory from the yaml. This information is used for the runtime data generation.
	errYaml, done := w.getYamlData()
	if done {
		return workload.QueryLoad{}, errYaml
	}
	// Parse transactions from the sql file.
	readPath := filepath.Join(w.outputDir, fmt.Sprintf("%s_read.sql", w.dbName))
	writePath := filepath.Join(w.outputDir, fmt.Sprintf("%s_write.sql", w.dbName))
	readTransactions, errRead := readSQL(readPath)
	writeTransactions, errWrite := readSQL(writePath)
	if errRead != nil {
		return workload.QueryLoad{}, errRead
	}
	if errWrite != nil {
		return workload.QueryLoad{}, errWrite
	}

	db, err := gosql.Open("postgres", strings.Join(urls, " "))
	if err != nil {
		return workload.QueryLoad{}, err
	}
	db.SetMaxOpenConns(w.connFlags.Concurrency + 1)
	db.SetMaxIdleConns(w.connFlags.Concurrency + 1)

	//initialise teh generators and column old data caches
	if err := w.initGenerators(db); err != nil {
		return workload.QueryLoad{}, err
	}

	ql := workload.QueryLoad{}
	for i := 0; i < w.connFlags.Concurrency; i++ {
		worker := &txnWorker{
			db:                db,
			readTransactions:  readTransactions,
			writeTransactions: writeTransactions,
			rng:               rand.New(rand.NewPCG(uint64(time.Now().UnixNano()), uint64(i))),
			hists:             reg.GetHandle(),
			d:                 w, // reference to the workloadGeneratorStruct for generators
		}
		ql.WorkerFns = append(ql.WorkerFns, worker.run)
	}
	ql.Close = func(context.Context) error { return db.Close() }
	return ql, nil
}

// setDbName registers the database name in the main workload struct.
// It uses the name provided using the --db flag, otherwise falls back to "workload_generator".
func (w *workloadGeneratorStruct) setDbName() {
	dbName := w.Meta().Name
	if w.connFlags.DBOverride != "" {
		dbName = w.connFlags.DBOverride
	}
	w.dbName = dbName
}

// getYamlData first checks whether the input yaml flag is set or not.
// Accordingly, it loads the schema information into memory from the correct location.
func (w *workloadGeneratorStruct) getYamlData() (error, bool) {
	var path string
	if w.inputYAML != "" {
		path = w.inputYAML
	} else {
		path = fmt.Sprintf("schema_%s.yaml", w.dbName)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return errors.Wrapf(err, "could not read schema YAML from %s", path), true
	}
	if err := yaml.Unmarshal(raw, &w.workloadSchema); err != nil {
		return errors.Wrapf(err, "couldn't unmarshal schema YAML"), true
	}
	return nil, false
}

// getRegularColumnValue picks values from the generator or cache depending on sql clause or whether there is a fk dependency.
func (w *workloadGeneratorStruct) getRegularColumnValue(p Placeholder, idx int) string {
	tableName := getTableName(p, w)
	key := fmt.Sprintf("%s.%s", tableName, p.Name)
	rc := w.columnGens[key]
	rc.mu.Lock()
	defer rc.mu.Unlock()

	// for filling in data for where clause or columns with foreign key constraints, we use the cache.
	if p.Clause == "WHERE" || (rc.columnMeta.HasForeignKey == true) {
		if len(rc.cache) > 0 {
			return rc.cache[idx]
		}
	}
	// for insert or update clauses, we use the generator to get a new value.
	v := rc.gen.Next()
	if len(rc.cache) < maxCacheSize {
		rc.cache = append(rc.cache, v)
	} else {
		rc.cache[rand.IntN(len(rc.cache))] = v
	}
	return v
}

// txnWorker consists of all teh data that is needed for the runtime routines
type txnWorker struct {
	db                *gosql.DB //db is the connection to the running cluster.
	readTransactions  []Transaction
	writeTransactions []Transaction
	rng               *rand.Rand
	hists             *histogram.Histograms
	d                 *workloadGeneratorStruct // reference to the workloadGeneratorStruct for generators
}

// run executes a random transaction from the list of transactions.
func (t *txnWorker) run(ctx context.Context) error {
	txn := t.chooseTransaction()
	// Reference to the workloadGeneratorStruct for generators.
	d := t.d
	// Start time for the metrics.
	start := timeutil.Now()
	// Inserted maintains a map of column names to the values that were inserted in this transaction.
	inserted := make(map[string][]interface{})
	err := crdb.ExecuteTx(ctx, t.db, nil, func(tx *gosql.Tx) error {
		for _, sqlQuery := range txn.Queries {
			args := make([]interface{}, len(sqlQuery.Placeholders))
			// Checking if we have a situation where all the primary keys in the query have foreign key dependency.
			allPksAreFK := checkIfAllPkAreFk(sqlQuery, d)
			// Pick a single fkIdx for ALL FK placeholders (or -1 if none).
			// This ensures that for all column in a composite fk, the same row index from the parent column cache is chosen.
			fkIndex := t.pickForeignKeyIndex(sqlQuery, d)
			// Build per-placeholder indexes.
			indexes := t.setCacheIndex(sqlQuery, d, fkIndex)
			for i, placeholder := range sqlQuery.Placeholders {
				var raw string
				// Getting the value to be inserted for the placeholder
				raw = getColumnValue(allPksAreFK, placeholder, d, inserted, raw, indexes, i)
				// If the data was generated to be written, we need to insert it into the inserted map
				if placeholder.Clause == insert || placeholder.Clause == update {
					inserted[placeholder.Name] = append(inserted[placeholder.Name], raw)
				}
				// Set the value for the placeholder in the args slice based on the column type
				err := setColumnValue(raw, placeholder, args, i)
				if err != nil {
					return err
				}
			}
			// Run the SQL query with the args
			if _, err := tx.ExecContext(ctx, sqlQuery.SQL, args...); err != nil {
				return err
			}
		}
		return nil
	})
	// Calculate the elapsed time for the transaction metrics
	elapsed := timeutil.Since(start)
	t.hists.Get(fmt.Sprintf("typ_%v", txn.typ)).Record(elapsed)
	return err
}

// chooseTransaction returns a random transaction of type read or write based on the readPct flag.
func (t *txnWorker) chooseTransaction() Transaction {
	var txn Transaction
	reads := t.readTransactions
	writes := t.writeTransactions

	// If neither set has any transactions, just return the zero-Txn.
	if len(reads) == 0 && len(writes) == 0 {
		return txn
	}
	// If there are no read txns, always pick a write transaction.
	if len(reads) == 0 {
		return writes[t.rng.IntN(len(writes))]
	}
	// If there are no write txns, always pick a read transaction.
	if len(writes) == 0 {
		return reads[t.rng.IntN(len(reads))]
	}

	// If both are non-empty then choose based on readPct.
	if t.rng.IntN(100) < t.d.readPct {
		return reads[t.rng.IntN(len(reads))]
	}
	return writes[t.rng.IntN(len(writes))]
}

// setColumnValue sets the value for a placeholder in the args slice.
func setColumnValue(raw string, placeholder Placeholder, args []interface{}, i int) error {
	var arg interface{}
	// If we got an empty string and this column is nullable, emit a SQL NULL.
	if raw == "" && placeholder.IsNullable {
		arg = setNullType(placeholder, arg)
	} else {
		// Otherwise parse the raw string into the right Go/sql type.
		typedValue, err := setNotNullType(placeholder, raw, arg)
		if err != nil {
			return err
		}
		arg = typedValue
	}

	args[i] = arg
	return nil
}

// setNotNullType converts the raw string value to the appropriate SQL type based on the placeholder's column type.
func setNotNullType(placeholder Placeholder, raw string, arg interface{}) (interface{}, error) {
	switch t := strings.ToUpper(placeholder.ColType); {
	// integer types
	case strings.HasPrefix(t, "INT"):
		iv, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return nil, err
		}
		arg = sql.NullInt64{Int64: iv, Valid: true}
	// floating point types
	case strings.HasPrefix(t, "FLOAT"), strings.HasPrefix(t, "DECIMAL"), strings.HasPrefix(t, "NUMERIC"), strings.HasPrefix(t, "DOUBLE"):
		fv, err := strconv.ParseFloat(raw, 64)
		if err != nil {
			return nil, err
		}
		arg = sql.NullFloat64{Float64: fv, Valid: true}
	// boolean types
	case t == "BOOL", t == "BOOLEAN":
		bv, err := strconv.ParseBool(raw)
		if err != nil {
			return nil, err
		}
		arg = sql.NullBool{Bool: bv, Valid: true}
	// remaining types are parsed as raw strings
	default:
		// treat everything else as text/varchar/etc.
		arg = sql.NullString{String: raw, Valid: raw != ""}
	}
	return arg, nil
}

// setNullType sets the argument to a SQL NULL value based on the column type of the placeholder.
func setNullType(placeholder Placeholder, arg interface{}) interface{} {
	switch t := strings.ToUpper(placeholder.ColType); {
	case strings.HasPrefix(t, "INT"):
		arg = sql.NullInt64{Valid: false}
	case strings.HasPrefix(t, "FLOAT"), strings.HasPrefix(t, "DECIMAL"), strings.HasPrefix(t, "NUMERIC"), strings.HasPrefix(t, "DOUBLE"):
		arg = sql.NullFloat64{Valid: false}
	case t == "BOOL", t == "BOOLEAN":
		arg = sql.NullBool{Valid: false}
	default:
		arg = sql.NullString{Valid: false}
	}
	return arg
}

// getTableName checks if the name field of placeholder is a column in the TableName column in the allSchema map inside d.
// If yes, then returns that table name. otherwise looks for a table with that column and returns that.
func getTableName(p Placeholder, d *workloadGeneratorStruct) string {
	for _, block := range d.workloadSchema[p.TableName] {
		for colName, _ := range block.Columns {
			if colName == p.Name {
				return p.TableName
			}
		}
	}
	for tableName, blocks := range d.workloadSchema {
		block := blocks[0]
		for colName, _ := range block.Columns {
			if colName == p.Name {
				return tableName
			}
		}
	}
	return p.TableName
}

// getColumnValue retrieves the value for a placeholder based on its clause and whether it has a foreign key dependency.
func getColumnValue(allPksAreFK bool, p Placeholder, d *workloadGeneratorStruct, inserted map[string][]interface{}, raw string, indexes []int, i int) string {
	if allPksAreFK && (p.Clause == insert || p.Clause == update) {
		tableName := getTableName(p, d)
		key := fmt.Sprintf("%s.%s", tableName, p.Name)
		fk := d.columnGens[key].columnMeta.FK
		parts := strings.Split(fk, ".")
		parentCol := parts[len(parts)-1] // last part is the column name
		if vals, ok := inserted[parentCol]; ok && len(vals) > 0 {
			raw = vals[0].(string)         // use the first value from the inserted map
			inserted[parentCol] = vals[1:] // remove the first value
		} else {
			//Fallback that shouldn't really happen.
			raw = d.getRegularColumnValue(p, indexes[i])
		}
	} else {
		raw = d.getRegularColumnValue(p, indexes[i])
	}
	return raw
}

// setCacheIndex sets the indexes for each placeholder in the SQL query.
// If the placeholder is a foreign key, it uses the fkIdx; otherwise, it picks a random index from the cache.
func (t *txnWorker) setCacheIndex(sqlQuery SQLQuery, d *workloadGeneratorStruct, fkIdx int) []int {
	indexes := make([]int, len(sqlQuery.Placeholders))
	for i, p := range sqlQuery.Placeholders {
		tableName := getTableName(p, d)
		key := fmt.Sprintf("%s.%s", tableName, p.Name)
		if d.columnGens[key].columnMeta.HasForeignKey {
			indexes[i] = fkIdx
		} else {
			cacheLen := len(d.columnGens[key].cache)
			indexes[i] = t.rng.IntN(cacheLen)
		}
	}
	return indexes
}

// pickForeignKeyIndex picks a random index from the cache of a foreign key column.
func (t *txnWorker) pickForeignKeyIndex(sqlQuery SQLQuery, d *workloadGeneratorStruct) int {
	fkIdx := -1
	for _, p := range sqlQuery.Placeholders {
		tableName := getTableName(p, d)
		key := fmt.Sprintf("%s.%s", tableName, p.Name)
		if d.columnGens[key].columnMeta.HasForeignKey {
			cacheLen := len(d.columnGens[key].cache)
			if cacheLen > 0 {
				fkIdx = t.rng.IntN(cacheLen)
			}
			break
		}
	}
	return fkIdx
}

// checkIfAllPkAreFk checks if all primary keys in the SQL query are foreign keys.
func checkIfAllPkAreFk(sqlQuery SQLQuery, d *workloadGeneratorStruct) bool {
	allPksAreFK := true
	for _, p := range sqlQuery.Placeholders {
		tableName := getTableName(p, d)
		key := fmt.Sprintf("%s.%s", tableName, p.Name)
		if p.IsPrimaryKey && !d.columnGens[key].columnMeta.HasForeignKey {
			allPksAreFK = false
			break
		}
	}
	return allPksAreFK
}
